---
title: "Exciting New Updates to TidyDensity: Enhancing Distribution Analysis!"
author: "Steven P. Sanderson II, MPH"
date: "2024-05-30"
categories: [code, rtip, operations]
toc: TRUE
---

# Introduction

Hello, fellow R enthusiasts! I'm thrilled to share some fantastic updates to the TidyDensity package. These updates bring a wealth of new features, functions, and enhancements, making distribution analysis more comprehensive and efficient. Let's dive into the details!

## New Features

### Negative Binomial Distribution

-   **util_negative_binomial_aic()**: Calculate the Akaike Information Criterion (AIC) for the negative binomial distribution. This function aids in model selection, helping you determine the best-fitting model for your data.

### Zero-Truncated Negative Binomial Distribution

-   **util_zero_truncated_negative_binomial_param_estimate()**: Estimate the parameters of the zero-truncated negative binomial distribution.
-   **util_zero_truncated_negative_binomial_aic()**: Calculate the AIC for the zero-truncated negative binomial distribution.
-   **util_zero_truncated_negative_binomial_stats_tbl()**: Create a summary table for the zero-truncated negative binomial distribution.

### Zero-Truncated Poisson Distribution

-   **util_zero_truncated_poisson_param_estimate()**: Estimate the parameters of the zero-truncated Poisson distribution.
-   **util_zero_truncated_poisson_aic()**: Calculate the AIC for the zero-truncated Poisson distribution.
-   **util_zero_truncated_poisson_stats_tbl()**: Create a summary table for the zero-truncated Poisson distribution.

### F Distribution

-   **util_f_param_estimate()**: Estimate the parameters for the F distribution.
-   **util_f_aic()**: Calculate the AIC for the F distribution.

### Zero-Truncated Geometric Distribution

-   **util_zero_truncated_geometric_param_estimate()**: Estimate the parameters of the zero-truncated geometric distribution.
-   **util_zero_truncated_geometric_aic()**: Calculate the AIC for the zero-truncated geometric distribution.
-   **util_zero_truncated_geometric_stats_tbl()**: Create a summary table for the zero-truncated geometric distribution.

### Triangular Distribution

-   **util_triangular_aic()**: Calculate the AIC for the triangular distribution.

### T Distribution

-   **util_t_param_estimate()**: Estimate the parameters of the T distribution.
-   **util_t_aic()**: Calculate the AIC for the T distribution.

### Pareto Type I Distribution

-   **util_pareto1_param_estimate()**: Estimate the parameters of the Pareto Type I distribution.
-   **util_pareto1_aic()**: Calculate the AIC for the Pareto Type I distribution.
-   **util_pareto1_stats_tbl()**: Create a summary table for the Pareto Type I distribution.

### Paralogistic Distribution

-   **util_paralogistic_param_estimate()**: Estimate the parameters of the paralogistic distribution.
-   **util_paralogistic_aic()**: Calculate the AIC for the paralogistic distribution.
-   **util_paralogistic_stats_tbl()**: Create a summary table for the paralogistic distribution.

### Inverse Weibull Distribution

-   **util_inverse_weibull_param_estimate()**: Estimate the parameters of the Inverse Weibull distribution.
-   **util_inverse_weibull_aic()**: Calculate the AIC for the Inverse Weibull distribution.
-   **util_inverse_weibull_stats_tbl()**: Create a summary table for the Inverse Weibull distribution.

### Inverse Pareto Distribution

-   **util_inverse_pareto_param_estimate()**: Estimate the parameters of the Inverse Pareto distribution.
-   **util_inverse_pareto_aic()**: Calculate the AIC for the Inverse Pareto distribution.
-   **util_inverse_pareto_stats_tbl()**: Create a summary table for the Inverse Pareto distribution.

### Inverse Gamma Distribution

-   **util_inverse_burr_param_estimate()**: Estimate the parameters of the Inverse Gamma distribution.
-   **util_inverse_burr_aic()**: Calculate the AIC for the Inverse Gamma distribution.
-   **util_inverse_burr_stats_tbl()**: Create a summary table for the Inverse Gamma distribution.

### Generalized Pareto Distribution

-   **util_generalized_pareto_param_estimate()**: Estimate the parameters of the Generalized Pareto distribution.
-   **util_generalized_pareto_aic()**: Calculate the AIC for the Generalized Pareto distribution.
-   **util_generalized_pareto_stats_tbl()**: Create a summary table for the Generalized Pareto distribution.

### Generalized Gamma Distribution

-   **util_generalized_beta_param_estimate()**: Estimate the parameters of the Generalized Gamma distribution.
-   **util_generalized_beta_aic()**: Calculate the AIC for the Generalized Gamma distribution.
-   **util_generalized_beta_stats_tbl()**: Create a summary table for the Generalized Gamma distribution.

### Zero-Truncated Binomial Distribution

-   **util_zero_truncated_binomial_stats_tbl()**: Create a summary table for the Zero Truncated binomial distribution.
-   **util_zero_truncated_binomial_param_estimate()**: Estimate the parameters of the Zero Truncated binomial distribution.
-   **util_zero_truncated_binomial_aic()**: Calculate the AIC for the Zero Truncated binomial distribution.

## Minor Improvements and Fixes

-   **util_negative_binomial_param_estimate()**: Updated to use `optim()` for parameter estimation, enhancing accuracy and efficiency.
-   **quantile_normalize()**: Added names to columns when `.return_tibble = TRUE` for better readability and usability.

## Conclusion

These updates significantly expand the functionality of TidyDensity, providing more tools for robust distribution analysis. Whether you're working with standard or specialized distributions, these new functions and improvements will streamline your workflow and enhance your analytical capabilities.

I encourage you to explore these new features and see how they can benefit your projects. As always, your feedback is invaluable, so please share your thoughts and experiences with these updates. Happy coding!
