---
title: "Officially on CRAN {tidyAML}"
author: "Steven P. Sanderson II, MPH"
date: "2023-02-16"
categories: [code, rtip, tidyaml]
---

# Introduction

I'm excited to announce that the R package {tidyAML} is now officially available on CRAN! This package is designed to make it easy for users to perform automated machine learning (AutoML) using the tidymodels ecosystem. With a simple and intuitive interface, tidyAML allows users to quickly generate high-quality machine learning models without worrying about the underlying details.

One of the key features of tidyAML is its ability to generate regression models on the fly, without the need to build a full specification or tune hyper-parameters. This makes it ideal for users who want to quickly build a machine learning model without spending a lot of time on the setup process.

tidyAML is also designed to be easy to use, with a set of functions that are straightforward and can generate many models and predictions at once. And because it's built on top of the tidymodels ecosystem, users don't need to worry about setting up additional packages or dependencies.

We're also happy to announce that tidyAML will be added to the R package {healthyverse} and pushed to CRAN this week. This means that users who install {healthyverse} will automatically get access to tidyAML, as well as other popular packages like ggplot2, dplyr, and tidyr.

Whether you're a beginner or an experienced machine learning practitioner, tidyAML is a powerful tool that can help you quickly generate high-quality models with minimal setup. We hope you'll give it a try and let us know what you think!