---
title: "Introducing TidyDensity Version 1.4.0: Enhancing Data Analysis in R"
author: "Steven P. Sanderson II, MPH"
date: "2024-04-29"
categories: [code, rtip, tidydensity]
---

# Introduction

I'm thrilled to announce the release of TidyDensity version 1.4.0, packed with exciting features and improvements to elevate your data analysis experience in R. Let's dive into what this latest update has to offer.

# New Features

## Quantile Normalization

Say goodbye to skewed data distributions! With the new `quantile_normalization()` function, you can now easily normalize your data using quantiles, ensuring more accurate and reliable analysis results.

## Duplicate Row Detection

Data integrity matters, which is why we've introduced the `check_duplicate_rows()` function. Quickly identify and eliminate duplicate rows in your data frame, streamlining your workflow and improving data quality.

## Chi-Square Distribution Parameter Estimation

Estimating parameters for the chi-square distribution is now a breeze with the `util_chisquare_param_estimate()` function. Empower your statistical analysis with precise parameter estimation capabilities.

## Markov Chain Monte Carlo (MCMC) Sampling

Unlock the power of Markov Chain Monte Carlo sampling with the new `tidy_mcmc_sampling()` function. Seamlessly sample from distributions using MCMC, and visualize the results with diagnostic plots for deeper insights into your data.

## AIC Calculation for Distributions

Making informed model selection decisions just got easier! TidyDensity now includes `util_dist_aic()` functions to calculate the Akaike Information Criterion (AIC) for various distributions, providing valuable metrics for model evaluation.

# Minor Fixes and Improvements

In addition to these exciting new features, we've also made several minor fixes and enhancements to further refine your user experience:

- Enhanced `tidy_multi_single_dist()` function to respect the `.return_tibble` parameter.
- Improved documentation, including updates related to MCMC usage.
- Updated `tidy_distribution_comparison()` to incorporate AIC calculations from dedicated `util_dist_aic()` functions.

# Upgrade Now!

Ready to supercharge your data analysis workflow? Upgrade to TidyDensity version 1.4.0 today and take advantage of these powerful new features and enhancements. Whether you're a seasoned data analyst or just getting started with R, TidyDensity is your go-to toolkit for streamlined and robust data analysis.

As always, we welcome your feedback and suggestions for future improvements. Stay tuned for more updates as we continue to evolve and enhance the TidyDensity package to meet your data analysis needs.

Happy analyzing!

*Steve, Manager of Applications at Stony Brook Medicine*

*Creator and Maintainer of TidyDensity*