{
  "hash": "52f179157dfc2b73f047c44d2b31f6b0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"How to Calculate Odds Ratios in R With Examples Using epitools\"\nauthor: \"Steven P. Sanderson II, MPH\"\ndate: \"2025-07-21\"\ncategories: [code, rtip]\ntoc: TRUE\ndescription: \"Learn how to calculate odds ratios in R using the epitools package with clear examples and simple syntax for R programmers.\"\nkeywords: [Programming, Odds Ratios in R, epitools package, oddsratio() function, Calculate odds ratios, R statistics, Contingency tables in R, Epidemiological analysis R, Risk analysis R, R programming examples, Statistical inference R, How to calculate odds ratios in R with epitools, Step-by-step odds ratio calculation using oddsratio() in R, Interpreting odds ratios from contingency tables in R, R code examples for odds ratio analysis, Using the oddsratio() function for epidemiological data in R]\n---\n\n\n\n# Introduction\n\nIf you're an R programmer working with categorical data, you'll often need to measure the association between two binary variables. That's where **odds ratios** come in handy! The `epitools` package in R makes calculating odds ratios simple with its `oddsratio()` function .\n\nIn this guide, we'll walk through everything you need to know about calculating odds ratios in R. You'll learn the function syntax, see practical examples, and understand how to interpret the results. Whether you're analyzing medical data, conducting epidemiological research, or exploring any binary relationships, this tutorial has you covered.\n\n# What Are Odds Ratios?\n\nAn **odds ratio (OR)** compares the odds of an event happening in one group versus another group. It's especially useful when you have two binary variables (yes/no, exposed/unexposed, success/failure) .\n\nHere's what the values mean:\n\n- **OR = 1**: No association between the variables\n- **OR > 1**: Positive association (higher odds in the first group)\n- **OR < 1**: Negative association (lower odds in the first group)\n\nFor example, if the odds ratio is 3.0, the odds of the outcome are 3 times higher in the exposed group compared to the unexposed group.\n\n# Installing and Loading epitools\n\nBefore we dive into calculations, let's get the `epitools` package ready:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Install the package (only need to do this once)\n#install.packages(\"epitools\")\n\n# Load the package\nlibrary(epitools)\n```\n:::\n\n\n\n# Understanding oddsratio() Syntax\n\nThe `oddsratio()` function has a straightforward syntax with several customizable options :\n\n```r\noddsratio(x, y = NULL, \n          method = c(\"midp\", \"fisher\", \"wald\", \"small\"), \n          conf.level = 0.95, \n          rev = c(\"neither\", \"rows\", \"columns\", \"both\"), \n          correction = FALSE, \n          verbose = FALSE)\n```\n\nLet's break down each parameter:\n\n| Parameter | Description | Default |\n|-----------|-------------|---------|\n| **x** | A 2x2 matrix or table of counts | Required |\n| **y** | Optional second vector (rarely used) | NULL |\n| **method** | Estimation method | \"midp\" |\n| **conf.level** | Confidence level (e.g., 0.95 for 95%) | 0.95 |\n| **rev** | Reverse table orientation | \"neither\" |\n| **correction** | Apply continuity correction | FALSE |\n| **verbose** | Print detailed output | FALSE |\n\n# Creating 2x2 Tables in R\n\nOdds ratios work with 2x2 contingency tables. Here's how to create them :\n\n## Method 1: Using matrix()\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a 2x2 table\ndata <- matrix(c(30, 70, 10, 90), nrow = 2, byrow = TRUE)\n\n# Add row and column names for clarity\nrownames(data) <- c(\"Exposed\", \"Unexposed\")\ncolnames(data) <- c(\"Disease\", \"No Disease\")\n\n# View the table\nprint(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Disease No Disease\nExposed        30         70\nUnexposed      10         90\n```\n\n\n:::\n:::\n\n\n\n## Method 2: Using a Data Frame\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a data frame\ndf <- data.frame(\n  exposure = c(rep(\"Exposed\", 100), rep(\"Unexposed\", 100)),\n  disease = c(rep(\"Yes\", 30), rep(\"No\", 70), \n              rep(\"Yes\", 10), rep(\"No\", 90))\n)\n\n# Convert to table\nmy_table <- table(df$exposure, df$disease)\nprint(my_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           \n            No Yes\n  Exposed   70  30\n  Unexposed 90  10\n```\n\n\n:::\n:::\n\n\n\n# Basic Examples with oddsratio()\n\nLet's calculate odds ratios with real examples :\n\n## Example 1: Simple Calculation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create the data\ndata1 <- matrix(c(30, 70, 10, 90), nrow = 2, byrow = TRUE)\nrownames(data1) <- c(\"Exposed\", \"Unexposed\")\ncolnames(data1) <- c(\"Disease\", \"No Disease\")\n\n# Calculate odds ratio\nresult <- oddsratio(data1, method = \"wald\")\nprint(result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n          Disease No Disease Total\nExposed        30         70   100\nUnexposed      10         90   100\nTotal          40        160   200\n\n$measure\n                        NA\nodds ratio with 95% C.I. estimate    lower   upper\n               Exposed   1.000000       NA      NA\n               Unexposed 3.857143 1.766603 8.42156\n\n$p.value\n           NA\ntwo-sided     midp.exact fisher.exact  chi.square\n  Exposed             NA           NA          NA\n  Unexposed 0.0004024082 0.0006504107 0.000406952\n\n$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n```\n\n\n:::\n:::\n\n\n\nBased on our computation results, this would give us:\n\n- **Odds Ratio**: 3.857\n- **95% CI**: 1.767 to 8.422\n- **p-value**: 0.0007\n\n## Example 2: Different Method Options\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using Fisher's exact method\nresult_fisher <- oddsratio(data1, method = \"fisher\")\ncat(\"Fisher's Exact Method Results:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFisher's Exact Method Results:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(result_fisher)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n          Disease No Disease Total\nExposed        30         70   100\nUnexposed      10         90   100\nTotal          40        160   200\n\n$measure\n                        NA\nodds ratio with 95% C.I. estimate    lower    upper\n               Exposed   1.000000       NA       NA\n               Unexposed 3.831525 1.684537 9.405984\n\n$p.value\n           NA\ntwo-sided     midp.exact fisher.exact  chi.square\n  Exposed             NA           NA          NA\n  Unexposed 0.0004024082 0.0006504107 0.000406952\n\n$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Conditional MLE & exact CI from 'fisher.test'\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Using mid-p method (default)\nresult_midp <- oddsratio(data1, method = \"midp\")\ncat(\"Mid-P Method Results:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMid-P Method Results:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(result_midp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n          Disease No Disease Total\nExposed        30         70   100\nUnexposed      10         90   100\nTotal          40        160   200\n\n$measure\n                        NA\nodds ratio with 95% C.I. estimate    lower    upper\n               Exposed   1.000000       NA       NA\n               Unexposed 3.796852 1.783145 8.728312\n\n$p.value\n           NA\ntwo-sided     midp.exact fisher.exact  chi.square\n  Exposed             NA           NA          NA\n  Unexposed 0.0004024082 0.0006504107 0.000406952\n\n$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"median-unbiased estimate & mid-p exact CI\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Using small sample adjustment\nresult_small <- oddsratio(data1, method = \"small\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in any(or, na.rm = TRUE): coercing argument of type 'double' to logical\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Small Sample Adjustment Results:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSmall Sample Adjustment Results:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(result_small)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n          Disease No Disease Total\nExposed        30         70   100\nUnexposed      10         90   100\nTotal          40        160   200\n\n$measure\n                        NA\nodds ratio with 95% C.I. estimate    lower    upper\n               Exposed   1.000000       NA       NA\n               Unexposed 3.457106 1.731167 8.031582\n\n$p.value\n           NA\ntwo-sided     midp.exact fisher.exact  chi.square\n  Exposed             NA           NA          NA\n  Unexposed 0.0004024082 0.0006504107 0.000406952\n\n$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"small sample-adjusted UMLE & normal approx (Wald) CI\"\n```\n\n\n:::\n:::\n\n\n\n# Interpreting the Results\n\nWhen you run `oddsratio()`, you get several key outputs :\n\n| Output | What It Means |\n|--------|---------------|\n| **Odds Ratio** | The strength of association |\n| **95% CI Lower** | Lower bound of confidence interval |\n| **95% CI Upper** | Upper bound of confidence interval |\n| **p-value** | Statistical significance test |\n\n> **Key Takeaway**: If the confidence interval includes 1, the association is not statistically significant at your chosen confidence level.\n\n# Real-World Examples\n\nLet's look at some practical scenarios:\n\n## Medical Study Example\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Smoking and lung cancer data\nsmoking_data <- matrix(c(15, 25, 5, 35), nrow = 2, byrow = TRUE)\nrownames(smoking_data) <- c(\"Smokers\", \"Non-smokers\")\ncolnames(smoking_data) <- c(\"Cancer\", \"No Cancer\")\n\nresult <- oddsratio(smoking_data, method = \"wald\")\ncat(\"Smoking and Lung Cancer Results:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSmoking and Lung Cancer Results:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n            Cancer No Cancer Total\nSmokers         15        25    40\nNon-smokers      5        35    40\nTotal           20        60    80\n\n$measure\n                        NA\nodds ratio with 95% C.I. estimate    lower   upper\n             Smokers          1.0       NA      NA\n             Non-smokers      4.2 1.350224 13.0645\n\n$p.value\n             NA\ntwo-sided     midp.exact fisher.exact  chi.square\n  Smokers             NA           NA          NA\n  Non-smokers 0.01128547   0.01877238 0.009823275\n\n$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n```\n\n\n:::\n:::\n\n\n\nFrom our calculations, this gives:\n\n- **Odds Ratio**: 4.200\n- **95% CI**: 1.350 to 13.065\n- **p-value**: 0.011\n\nThis means smokers have 4.2 times higher odds of cancer compared to non-smokers.\n\n## Small Sample Example\n\nWhen dealing with small samples, use appropriate methods:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sparse data\nsparse_data <- matrix(c(2, 8, 1, 19), nrow = 2, byrow = TRUE)\nresult_sparse <- oddsratio(sparse_data, method = \"fisher\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in chisq.test(xx, correct = correction): Chi-squared approximation may\nbe incorrect\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sparse Data Results:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSparse Data Results:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(result_sparse)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n          Outcome\nPredictor  Disease1 Disease2 Total\n  Exposed1        2        8    10\n  Exposed2        1       19    20\n  Total           3       27    30\n\n$measure\n          odds ratio with 95% C.I.\nPredictor  estimate     lower    upper\n  Exposed1 1.000000        NA       NA\n  Exposed2 4.480431 0.2060739 293.9622\n\n$p.value\n          two-sided\nPredictor  midp.exact fisher.exact chi.square\n  Exposed1         NA           NA         NA\n  Exposed2  0.2807882    0.2512315  0.1967056\n\n$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Conditional MLE & exact CI from 'fisher.test'\"\n```\n\n\n:::\n:::\n\n\n\nResults:\n\n- **Odds Ratio**: 4.48\n- **95% CI**: 0.206 to 293.962\n- **p-value**: 0.251\n\nNote the wide confidence interval due to small sample size!\n\n# Visualizing Odds Ratios\n\nVisual representations help communicate your findings. Here are the odds ratios from our examples:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load necessary libraries\nlibrary(ggplot2)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\n# Create a data frame for plotting\nodds_data <- data.frame(\n  Group = c(\"Exposed\", \"Unexposed\", \"Smokers\", \"Non-smokers\"),\n  Odds_Ratio = c(3.857, 1, 4.200, 1),\n  Lower_CI = c(1.767, NA, 1.350, NA),\n  Upper_CI = c(8.422, NA, 13.065, NA)\n)\n# Plot the odds ratios with confidence intervals\nggplot(odds_data, aes(x = Group, y = Odds_Ratio)) +\n  geom_point() +\n  geom_errorbar(aes(ymin = Lower_CI, ymax = Upper_CI), width = 0.2) +\n  geom_hline(yintercept = 1, linetype = \"dashed\", color = \"red\") +\n  labs(title = \"Odds Ratios with 95% Confidence Intervals\",\n       y = \"Odds Ratio\",\n       x = \"Group\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\nThe plot shows odds ratios with 95% confidence intervals. The dashed line at OR=1 represents no association.\n\nHere's how the data looks in a contingency table:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a contingency table for visualization\ncontingency_table <- matrix(c(30, 70, 10, 90), nrow = 2, byrow = TRUE)\nrownames(contingency_table) <- c(\"Exposed\", \"Unexposed\")\ncolnames(contingency_table) <- c(\"Disease\", \"No Disease\")\n# Display the contingency table\nprint(contingency_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Disease No Disease\nExposed        30         70\nUnexposed      10         90\n```\n\n\n:::\n:::\n\n\n\n# Common Use Cases\n\nOdds ratios are widely used in:\n\n1. **Case-Control Studies**: Comparing disease cases with healthy controls\n2. **Clinical Trials**: Evaluating treatment effectiveness\n3. **Epidemiology**: Identifying risk factors for diseases\n4. **Cross-Sectional Studies**: Analyzing prevalence relationships\n5. **Public Health**: Informing policy decisions\n\n# Your Turn!\n\nTry calculating an odds ratio yourself! Given this vaccination data:\n\n|              | Got Flu | No Flu |\n|--------------|---------|--------|\n| Vaccinated   | 10      | 90     |\n| Unvaccinated | 30      | 70     |\n\n**Challenge**: Calculate the odds ratio using the `oddsratio()` function. What does it tell you about vaccine effectiveness?\n\n<details><summary>Click here for Solution!</summary>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create the table\nvaccine_data <- matrix(c(10, 90, 30, 70), nrow = 2, byrow = TRUE)\nrownames(vaccine_data) <- c(\"Vaccinated\", \"Unvaccinated\")\ncolnames(vaccine_data) <- c(\"Got Flu\", \"No Flu\")\n\n# Calculate odds ratio\nlibrary(epitools)\nresult <- oddsratio(vaccine_data, method = \"wald\")\nprint(result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$data\n             Got Flu No Flu Total\nVaccinated        10     90   100\nUnvaccinated      30     70   100\nTotal             40    160   200\n\n$measure\n                        NA\nodds ratio with 95% C.I.  estimate     lower     upper\n            Vaccinated   1.0000000        NA        NA\n            Unvaccinated 0.2592593 0.1187428 0.5660582\n\n$p.value\n              NA\ntwo-sided        midp.exact fisher.exact  chi.square\n  Vaccinated             NA           NA          NA\n  Unvaccinated 0.0004024082 0.0006504107 0.000406952\n\n$correction\n[1] FALSE\n\nattr(,\"method\")\n[1] \"Unconditional MLE & normal approximation (Wald) CI\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# The odds ratio should be approximately 0.259\n# This means vaccinated people have about 74% lower odds of getting flu\n# (1 - 0.259 = 0.741 or 74.1% reduction)\n```\n:::\n\n\n</details>\n\n# Quick Takeaways\n\n- **Odds ratios** measure association between two binary variables\n- Use `epitools::oddsratio()` for easy calculation in R\n- The function requires a 2x2 contingency table\n- Choose the right method based on sample size:\n  - Large samples: \"wald\"\n  - Small samples: \"fisher\" or \"midp\"\n- Always check confidence intervals for statistical significance\n- OR > 1 means positive association, OR < 1 means negative association\n- Wide confidence intervals indicate uncertainty (often due to small samples)\n\n# Conclusion\n\nCalculating **odds ratios in R** using the `epitools` package is straightforward once you understand the basics. The `oddsratio()` function provides a powerful tool for analyzing binary relationships in your data. \n\nRemember to:\n\n- Structure your data as a 2x2 table\n- Choose the appropriate estimation method\n- Interpret both the odds ratio and its confidence interval\n- Consider sample size when drawing conclusions\n\n# FAQs\n\n**Q1: What's the difference between odds ratio and risk ratio?**\nA: Odds ratios compare odds (probability of event/probability of no event), while risk ratios compare probabilities directly. Odds ratios are preferred in case-control studies where risk cannot be directly calculated.\n\n**Q2: When should I use Fisher's method instead of Wald?**\nA: Use Fisher's method when you have small sample sizes (any cell count < 5) or sparse data. It provides exact p-values rather than approximations.\n\n**Q3: How do I handle tables larger than 2x2?**\nA: The `oddsratio()` function only works with 2x2 tables. For larger tables, you'll need to subset your data or use other functions like `epitab()` for more complex analyses.\n\n**Q4: What does it mean if my confidence interval is very wide?**\nA: A wide confidence interval indicates high uncertainty in your estimate, usually due to small sample sizes. Consider collecting more data or using methods designed for small samples.\n\n**Q5: Can I use odds ratios for non-binary variables?**\nA: No, odds ratios are specifically for binary (two-category) variables. For variables with more categories, consider other measures like relative risk ratios or multinomial logistic regression.\n\n*Found this guide helpful? Share it with fellow R programmers and let us know what topics you'd like us to cover next! Follow us for more R programming tutorials and statistical analysis guides.*\n\n# References\n\n1. [https://cran.r-project.org/web/packages/epitools/index.html](https://cran.r-project.org/web/packages/epitools/index.html)\n\n2. [https://www.statology.org/odds-ratio-in-r/](https://www.statology.org/odds-ratio-in-r/)\n\n3. [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6532386/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6532386/)\n\n4. [https://stats.oarc.ucla.edu/other/mult-pkg/faq/general/faq-how-do-i-interpret-odds-ratios-in-logistic-regression/](https://stats.oarc.ucla.edu/other/mult-pkg/faq/general/faq-how-do-i-interpret-odds-ratios-in-logistic-regression/)\n\n\n------------------------------------------------------------------------\n\nHappy Coding! 🚀\n\n![odds Ratio in R](todays_post.png)\n\n------------------------------------------------------------------------\n\n*You can connect with me at any one of the below*:\n\n*Telegram Channel here*: <https://t.me/steveondata>\n\n*LinkedIn Network here*: <https://www.linkedin.com/in/spsanderson/>\n\n*Mastadon Social here*: [https://mstdn.social/\\@stevensanderson](https://mstdn.social/@stevensanderson)\n\n*RStats Network here*: [https://rstats.me/\\@spsanderson](https://rstats.me/@spsanderson)\n\n*GitHub Network here*: <https://github.com/spsanderson>\n\n*Bluesky Network here*: <https://bsky.app/profile/spsanderson.com>\n\n*My Book: Extending Excel with Python and R* here: <https://packt.link/oTyZJ>\n\n*You.com Referral Link*: <https://you.com/join/EHSLDTL6>\n\n------------------------------------------------------------------------\n\n\n\n```{=html}\n<script src=\"https://giscus.app/client.js\"\n        data-repo=\"spsanderson/steveondata\"\n        data-repo-id=\"R_kgDOIIxnLw\"\n        data-category=\"Comments\"\n        data-category-id=\"DIC_kwDOIIxnL84ChTk8\"\n        data-mapping=\"url\"\n        data-strict=\"0\"\n        data-reactions-enabled=\"1\"\n        data-emit-metadata=\"0\"\n        data-input-position=\"top\"\n        data-theme=\"dark\"\n        data-lang=\"en\"\n        data-loading=\"lazy\"\n        crossorigin=\"anonymous\"\n        async>\n</script>\n```\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}